# Generated by Django 3.0.5 on 2020-05-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='description',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
    ]
