# Generated by Django 3.0.5 on 2020-05-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_albums_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='img',
            field=models.ImageField(default='null', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='albums',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='albums',
            name='description',
            field=models.TextField(),
        ),
    ]
